version: '3.8'

services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recruitment
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ["./wait-for-it.sh", "db:5432", "--", "go", "run", "main.go"]
    env_file:
      - .env

volumes:
  db_data:
